# Generated by Django 5.1.6 on 2025-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_des', models.CharField(max_length=100)),
                ('pro_qun', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
